### ISSUE TITLE
コマンドラインの文字が入れ替わっています

### ISSUE THREAD

**Issue by y-masutani** [irvs/rosbook_jp#39]
コマンドラインの「-」が「−」に，「'」が「’」に，「*」が「∗」に置き換わっているために，PDFからシェルへコピペして使うことができません．これは不便ですし，文字の違いtだと気が付かないと謎のエラーに悩まされることになります．

**Comment by Kurazume** [comment]
Ubuntuのドキュメントビューアでは，問題なくコピペできるようです．Viewerの問題でしょうか．

**Comment by y-masutani** [comment]
当方でも，Ubuntu 14.04LTSの上でドキュメントビューアー（evince）3.10.3を使っています．

**Comment by y-masutani** [comment]
特別なことは何もしていません．インストールしたばかりのUbuntuで試しました．この本を読むには，追加でフォントのインストールが必要ですか？

**Comment by Kurazume** [comment]
失礼しました．私の方でも，文字が入れ替わる問題を確認しました．

**Comment by Kurazume** [comment]
code.texを以下のようにすれば，フォントが変わりますが直るようですね．

\lstdefinelanguage{ROS}{
  keywords={
  roscd,rospd,rosd,rosls,rosed,roscp,roscore,rosrun,roslaunch,rosclean,rosdep,rosdistro,
  rostopic,rosservice,rosnode,rosparam,rosmsg,rossrv,roswtf,rosversion,
  rosbag,catkin_create_pkg,catkin_eclipse,catkin_find,catkin_generate_changelog,
  catkin_init_workspace,catkin_make,rqt,rqt_plot,rqt_graph,rqt_bag,
  sudo,apt-get,install,cd,mkdir,make,cp,ntpdate,gedit,nano,ssh,
  ls,rm,sh,wget,update,upgrade,apt,get,ifconfig,source,git,qtcreator,cm,hg},
  comment=[l]{//},
  basicstyle=\ttfamily\small,　　←　これを追加
  literate={\$}{{\textcolor{red}\$}}1
}

**Comment by y-masutani** [comment]
WindowsのAcrobatでもNGでした．

**Comment by y-masutani** [comment]
コマンドラインの表現には，\ttfamilyが向いていると思います．

**Comment by Yuuta-watanabe** [comment]
y-masutaniさん

ありがとうございます．
chapter2.texとcode.texの修正を致しました.

**Comment by y-masutani** [comment]
対応ありがとうございました．http://irvs.github.io/rosbook_jp/ にはどんなスケジュールで反映されますか？
