### ISSUE TITLE
PDFを適切に作成する手順

### ISSUE THREAD

**Issue by y-masutani** [irvs/rosbook_jp#40]
PDFを適切に作成する手順を教えていただけないでしょうか。どこかに書いてありますか？

以下のようにして、手探りでPDFができるところまでは辿り着いたのですが、参照が??のまま残っていたり、章の最初の画像がなかったりと、うまくできていないようです。
```
git clone https://github.com/irvs/rosbook_jp.git
cd rosbook_jp
sudo apt-get install texlive-latex-base texlive-latex-extra texlive-lang-cjk texlive-bibtex-extra cm-super texlive-fonts-recommended texlive-fonts-extra
sh latex.sh

```

**Comment by Kurazume** [comment]
ほぼ同じですが
http://irvs.github.io/rosbook_jp/
の最後にありますように

sudo apt-get install texlive*
git clone https://github.com/irvs/rosbook_jp.git
cd rosbook_jp
sh latex.sh

です．参照の？を消すには
sh latex.sh
を何度か繰り返してください．

**Comment by y-masutani** [comment]
そこに書いてありましたか！見逃しておりました。申し訳ありません。
sh latex.shを2回実行すると、問題は解決しました。

ところが、できあがったものは、 http://irvs.github.io/rosbook_jp/ で公開されているものとページ番号が異なります。見比べたところ、コマンドラインのフォントが変わったためにページの配置がずれたのではないかと思います。内容が変わったわけではないので、ページ番号は保たれる方がいいですよね？

**Comment by y-masutani** [comment]
code.tex の中の、\lstdefinelanguage{ROS}{において
```
  basicstyle=\ttfamily,
```
とありましたが、これを @Kurazume 先生が書かれていたように、
```
  basicstyle=\ttfamily\small,
```
とすれば、ページ番号が合うようになりました。

**Comment by Kurazume** [comment]
ありがとうございます。
basicstyle=\ttfamily\small　としたものをアップしました。
例えば22頁など、若干、体裁が変わってしまうようですね。

**Comment by y-masutani** [comment]
22頁ですか？
私の環境では違いがわかりません。

**Comment by Kurazume** [comment]
３１ページでした。一行入りきらないようです。

**Comment by y-masutani** [comment]
確認しました。次のページで吸収されているので、まあよろしいかと…
それよりも、2行になる場合に2行目のインデントがコマンドラインの実際の体裁とは異なるのが気になります。
