### ISSUE TITLE
3章の問題点

### ISSUE THREAD

**Issue by y-masutani** [irvs/rosbook_jp#41]
69ページのCMakeLists.txt： 3行に分けて書くべき内容が，最後の1行になっています．

70ページのhello_world_node.cpp： main()関数の引数の「*」が別の文字になっています．コピペするとコンパイルエラーになります．プログラムリストやデータファイルの内容を示すときもフォントは \ttfamily を使う方がいいと思います．

**Comment by Kurazume** [comment]
ありがとうございます。修正したものをアップしました。

**Comment by y-masutani** [comment]
ありがとうございます。こちらでPDFを生成して、修正されていることを確認しました。

ところで、コピペした場合にインデントが維持できるようにできないでしょうか？
