### ISSUE TITLE
p.35 2.2.1 ROSの環境設定のご質問

### ISSUE THREAD

**Issue by StrawberryLab** [irvs/rosbook_jp#42]
.bashrc ファイルの追加部分

9: # Set ROS alias command
10: alias cw=’cd ~/catkin_ws’
11: alias cs=’cd ~/catkin_ws/src’
12: alias cm=’cd ~/catkin_ws && catkin_make’

を設定したところ、新しくターミナルを起動すると、
bash: alias: /home/hidetoshi/catkin_ws’: 見つかりません
bash: alias: /home/hidetoshi/catkin_ws/src’: 見つかりません
bash: alias: /home/hidetoshi/catkin_ws: 見つかりません

と表示されます。短縮コマンドの設定がうまくできてないように思いますが、どのようにすれば解決できるのでしょうか？
独学で学んでおり、初歩的な質問で恐縮ですが、何卒よろしくお願いいたします。

**Comment by Kurazume** [comment]
alias cw=’cd ~/catkin_ws’　等では、
’
ではなく
'
を使用してみてください。似ていますが、違うものです。

**Comment by StrawberryLab** [comment]
ご回答頂き、ありがとうございました。
解決出来ました。初歩的なミスで大変失礼いたしました。
