### ISSUE TITLE
p.70 3.4.6 ノードの実行のご質問

### ISSUE THREAD

**Issue by StrawberryLab** [irvs/rosbook_jp#43]
$ rosrun my_first_ros_pkg hello_world_node
を実行すると、
[rosrun] Couldn't find executable named hello_world_node below /home/hidetoshi/catkin_ws/src/my_first_ros_pkg
と表示されます。
hidetoshi@ubuntu01:~/catkin_ws/src/my_first_ros_pkg$ cd src
hidetoshi@ubuntu01:~/catkin_ws/src/my_first_ros_pkg/src$ ls
hello_world_node.cpp  hello_world_node.cpp~
のように、my_first_ros_pkg/srcの下にhello_world_node.cppがあることは確認しています。
どのようにすれば解決できるのでしょうか。大変申し訳ありませんが、何卒よろしくお願いいたします。

**Comment by Kurazume** [comment]
3.4.5 パッケージのビルド
の
cd ~/catkin_ws && catkin_make
あるいは
cm
はされましたでしょうか．

**Comment by StrawberryLab** [comment]
cd ~/catkin_ws && catkin_make
は行っていますが、うまく行きません。

**Comment by StrawberryLab** [comment]
$ export | grep ROS
を実行し、環境が適切にセットアップされているかを確認しました。以下に実行結果を記します。

hidetoshi@ubuntu01:~$ export | grep ROS
declare -x ROSLISP_PACKAGE_DIRECTORIES="/home/hidetoshi/catkin_ws/devel/share/common-lisp"
declare -x ROS_DISTRO="indigo"
declare -x ROS_ETC_DIR="/opt/ros/indigo/etc/ros"
declare -x ROS_HOSTNAME="192.168.3.4"
declare -x ROS_MASTER_URI="http://192.168.3.4:11311"
declare -x ROS_PACKAGE_PATH="/home/hidetoshi/catkin_ws/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks"
declare -x ROS_ROOT="/opt/ros/indigo/share/ros"
hidetoshi@ubuntu01:~$ 

何か問題解決の手がかりはありませんでしょうか。

**Comment by Yuuta-watanabe** [comment]
cd ~/catkin_ws && catkin_make
がうまくいかないとありますが、
エラー文として、どのようなものがでてますか？

**Comment by Kurazume** [comment]
cd ~/catkin_ws && catkin_make
で，エラーが出ていないでしょうか．
[100%] ．．．　という表示で終わっていますか？

**Comment by StrawberryLab** [comment]
[100%] ．．．　という表示で終わっていませんでした。以下にターミナルの結果を記載いたします。

hidetoshi@ubuntu01:~$ cd ~/catkin_ws && catkin_make
Base path: /home/hidetoshi/catkin_ws
Source space: /home/hidetoshi/catkin_ws/src
Build space: /home/hidetoshi/catkin_ws/build
Devel space: /home/hidetoshi/catkin_ws/devel
Install space: /home/hidetoshi/catkin_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/hidetoshi/catkin_ws/build"
####
####
#### Running command: "make -j8 -l8" in "/home/hidetoshi/catkin_ws/build"
####

これは何が問題なのでしょう?

**Comment by Kurazume** [comment]
[ 98%] Built target tracker
[100%] Built target urg_node
などで終わっていない場合には、コンパイルエラーです。
Error ... などで始まる行に問題が示されています。

コンパイルエラーについては、ROSではなく、C++の内容になりますので、
できるだけご自身で解決してみてください。

hello_world_node.cpp~
と比較すると、わかるかもしれません。

**Comment by StrawberryLab** [comment]
解決しました。
p.62 package.xml
p.69 CMakeLists.txt
の編集の流れがしっかりとできていませんでした。

package.xmlとCMakeLists.txtの編集を正しく行い、
cd ~/catkin_ws && catkin_make
をすると
[100%] Built target hello_world_node
が表示され、きちんとコンパイルができました。

ご協力ありがとうございました。

2016年9月9日 16:34 Kurazume <notifications@github.com>:
