### ISSUE TITLE
p.102 rosbag info only_cmd_vel.bagについてご質問

### ISSUE THREAD

**Issue by StrawberryLab** [irvs/rosbook_jp#44]
$ rosbag info only_cmd_vel.bag
path: only_cmd_vel.bag
version: 2.0
size: 4.0 KB

までは表示させることができました。その後の、

rt@rt:~$ rosbag info only_cmd_vel.bag
path: only_cmd_vel.bag
version: 2.0
duration: 5.9s
start: Jul 16 2015 19:08:32.09 (1437041312.09)
end: Jul 16 2015 19:08:38.03 (1437041318.03)
size: 14.7 KB
messages: 92
compression: none [1/1 chunks]
types: geometry_msgs/Twist [9f195f881246fdfa2798d1d3eebca84a]
topics: /turtle1/cmd_vel
92 msgs
: geometry_msgs/Twist

を表示させることができません。rt@rt:~$ rosbag info only_cmd_vel.bagがよくわからなかったのですが、
これは1行目と同じコマンドですよね? rt@rt:とは何でしょう?
見当違いな質問だったらすみません。何卒よろしくお願いいたします。

**Comment by Yuuta-watanabe** [comment]
ユーザ名@コンピュータ名です。
これはUbuntuの仕様なので、
コマンドをするときは、$　より右の部分をコピペ、もしくはタイプするようにしてください。

**Comment by Kurazume** [comment]
ここだけ　rt@rt:~$ rosbag info only_cmd_vel.bag　は間違いですね．
$ rosbag info only_cmd_vel.bag
に，修正します．

**Comment by Kurazume** [comment]
修正しました。ご指摘、ありがとうございました。

**Comment by StrawberryLab** [comment]
$ rosbag info only_cmd_vel.bag
をしても
path: only_cmd_vel.bag
version: 2.0
size: 4.0 KB
しか表示されない理由が判明しました。
$ rosbag record -O msglog.bag -a
を行ったターミナルで以降の作業
$ rosbag info msglog.bag
$ rosbag filter msglog.bag only_cmd_vel.bag "topic == ’/turtle1/cmd_vel’"
$ rosbag info only_cmd_vel.bag
と続かなければならなかったのですね。
$ rosbag record -O msglog.bag -aを行ったターミナルとは異なる新しいターミナルを開いて作業を行っていました。教科書の文を見落としてしまっていました。申し訳ありません。
正しく作業すると、教科書のように表示されました。
ご協力、ありがとうございました。
