### ISSUE TITLE
p.122 uvc_camera_nodeの実行に関してのご質問

### ISSUE THREAD

**Issue by StrawberryLab** [irvs/rosbook_jp#45]
$ rosrun uvc_camera uvc_camera_node
を実行すると、ターミナルに以下の文が表示され、中止されます。

[ WARN] [1473579822.954795813]: Camera calibration file /home/hidetoshi/.ros/camera_info/camera.yaml not found.
途中省略
terminate called after throwing an instance of 'std::runtime_error'
  what():  unable to start capture
中止 (コアダンプ)

これはなぜでしょうか?

**Comment by Yuuta-watanabe** [comment]
カメラを接続していない場合、以下のようにノードが落ちます。

rosrun uvc_camera uvc_camera_node 
[ INFO] [1473582711.854477297]: using default calibration URL
[ INFO] [1473582711.854573487]: camera calibration URL: file:///home/coi_5/.ros/camera_info/camera.yaml
[ INFO] [1473582711.854649526]: Unable to open camera calibration file [/home/coi_5/.ros/camera_info/camera.yaml]
[ WARN] [1473582711.854687671]: Camera calibration file /home/coi_5/.ros/camera_info/camera.yaml not found.
opening /dev/video0
terminate called after throwing an instance of 'std::runtime_error'
  what():  couldn't open /dev/video0
Aborted (core dumped)

まず /dev/video0 があるか確認してください。
find /dev/video0
でできます。

そのあと、
一応、ノードを起動して出力画面をすべて表示してもらってもいいですか？

**Comment by StrawberryLab** [comment]
/dev/video0の確認は以下のようになりました。
hidetoshi@ubuntu01:~$ find /dev/video0
/dev/video0

また、カメラを接続してrosrun uvc_camera uvc_camera_node を実行した結果を以下に記します。

hidetoshi@ubuntu01:~$ rosrun uvc_camera uvc_camera_node
[ INFO] [1473583836.256860339]: using default calibration URL
[ INFO] [1473583836.256988218]: camera calibration URL: file:///home/hidetoshi/.ros/camera_info/camera.yaml
[ INFO] [1473583836.257082637]: Unable to open camera calibration file [/home/hidetoshi/.ros/camera_info/camera.yaml]
[ WARN] [1473583836.257148379]: Camera calibration file /home/hidetoshi/.ros/camera_info/camera.yaml not found.
opening /dev/video0
pixfmt 0 = 'MJPG' desc = 'MJPEG'
  discrete: 640x480:   1/30 1/25 1/20 1/15 1/10 1/5 
  int (Brightness, 0, id = 980900): -255 to 255 (1)
  int (Contrast, 0, id = 980901): 0 to 30 (1)
  int (Saturation, 0, id = 980902): 0 to 127 (1)
  int (Hue, 0, id = 980903): -16000 to 16000 (1)
  bool (White Balance Temperature, Auto, 0, id = 98090c): 0 to 1 (1)
  int (Gamma, 0, id = 980910): 20 to 250 (1)
  menu (Power Line Frequency, 0, id = 980918): 0 to 2 (1)
    0: Disabled
    1: 50 Hz
    2: 60 Hz
  int (White Balance Temperature, 16, id = 98091a): 2500 to 7000 (1)
  int (Sharpness, 0, id = 98091b): 0 to 64 (1)
  int (Backlight Compensation, 0, id = 98091c): 0 to 2 (1)
terminate called after throwing an instance of 'std::runtime_error'
  what():  unable to start capture
中止 (コアダンプ)
hidetoshi@ubuntu01:~$

**Comment by Yuuta-watanabe** [comment]
別のuvc_cameraを使ってノードを起動してみてください。
ドライバー周辺に不具合があるのかもしれません。
