### ISSUE TITLE
p.145 6.3.5 ノードのビルドのご質問

### ISSUE THREAD

**Issue by StrawberryLab** [irvs/rosbook_jp#46]
irvs_ros_tutorialsパッケージのサービスファイル、サービスノードとクライアントノードをビルドする所で、以下のようなエラーが出ます。これは何が原因でしょうか？

hidetoshi@ubuntu01:~$ cd ~/catkin_ws
hidetoshi@ubuntu01:~/catkin_ws$ catkin_make
Base path: /home/hidetoshi/catkin_ws
Source space: /home/hidetoshi/catkin_ws/src
Build space: /home/hidetoshi/catkin_ws/build
Devel space: /home/hidetoshi/catkin_ws/devel
Install space: /home/hidetoshi/catkin_ws/install
#### 
#### 
#### 
#### 

[  0%] [  0%] Built target std_msgs_generate_messages_py
Built target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_cpp
[  7%] Built target hello_world_node
[  7%] Built target _irvs_ros_tutorials_generate_messages_check_deps_srvTutorial
[  7%] Built target _irvs_ros_tutorials_generate_messages_check_deps_msgTutorial
[ 46%] [ 53%] [ 69%] Built target irvs_ros_tutorials_generate_messages_lisp
Built target irvs_ros_tutorials_generate_messages_py
Built target irvs_ros_tutorials_generate_messages_cpp
[ 69%] [ 76%] Built target irvs_ros_tutorials_generate_messages
[ 84%] [ 92%] [100%] Built target ros_tutorial_msg_publisher
Built target ros_tutorial_msg_subscriber
Built target ros_tutorial_srv_client
Building CXX object irvs_ros_tutorials/CMakeFiles/ros_tutorial_srv_server.dir/src/ros_tutorial_srv_server.cpp.o
/home/hidetoshi/catkin_ws/src/irvs_ros_tutorials/src/ros_tutorial_srv_server.cpp:12:1: error: expected unqualified-id before numeric constant
 1
 ^
/home/hidetoshi/catkin_ws/src/irvs_ros_tutorials/src/ros_tutorial_srv_server.cpp: In function ‘bool calculation(irvs_ros_tutorials::srvTutorial::Request&, irvs_ros_tutorials::srvTutorial::Response&)’:
/home/hidetoshi/catkin_ws/src/irvs_ros_tutorials/src/ros_tutorial_srv_server.cpp:31:8: error: ‘g_operator’ was not declared in this scope
 switch(g_operator){
        ^
/home/hidetoshi/catkin_ws/src/irvs_ros_tutorials/src/ros_tutorial_srv_server.cpp:32:10: error: expected primary-expression before ‘:’ token
 case PLUS:
          ^
/home/hidetoshi/catkin_ws/src/irvs_ros_tutorials/src/ros_tutorial_srv_server.cpp:34:11: error: expected primary-expression before ‘:’ token
 case MINUS:
           ^
/home/hidetoshi/catkin_ws/src/irvs_ros_tutorials/src/ros_tutorial_srv_server.cpp:36:20: error: expected primary-expression before ‘:’ token
 case MULTIPLICATION:
                    ^
/home/hidetoshi/catkin_ws/src/irvs_ros_tutorials/src/ros_tutorial_srv_server.cpp:38:14: error: expected primary-expression before ‘:’ token
 case DIVISION:
              ^
/home/hidetoshi/catkin_ws/src/irvs_ros_tutorials/src/ros_tutorial_srv_server.cpp: In function ‘int main(int, char*_)’:
/home/hidetoshi/catkin_ws/src/irvs_ros_tutorials/src/ros_tutorial_srv_server.cpp:65:44: error: expected primary-expression before ‘)’ token
 nh_priv.setParam("calculation_method", PLUS);
                                            ^
/home/hidetoshi/catkin_ws/src/irvs_ros_tutorials/src/ros_tutorial_srv_server.cpp:81:40: error: ‘g_operator’ was not declared in this scope
 nh_priv.getParam("calculation_method", g_operator);
                                        ^
make[2]: *_\* [irvs_ros_tutorials/CMakeFiles/ros_tutorial_srv_server.dir/src/ros_tutorial_srv_server.cpp.o] エラー 1
make[1]: **\* [irvs_ros_tutorials/CMakeFiles/ros_tutorial_srv_server.dir/all] エラー 2
make: **\* [all] エラー 2
Invoking "make -j8 -l8" failed
hidetoshi@ubuntu01:~/catkin_ws$

**Comment by Yuuta-watanabe** [comment]
ソースコードはドラッグ&ドロップで記述したものでしょうか？

以下に同じソースコードがあるので、それで試してもらってもいいでしょうか。
https://github.com/irvs/irvs_ros_tutorials

ソースコードのダウンロードとmakeは本の150ページに書いてます。
catkin_makeする時、buildフォルダとdevelフォルダを念のため、
削除してから行ってみてください。
